version: "3"
services:
  doctor-ui:
    image: doctor-ui
    build:
      context: .
      dockerfile: DoctorUI/Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - patient-service
    networks:
      - extranet
      - intranet
  patient-ui:
    image: patient-ui
    build:
      context: PatientUI
      dockerfile: Dockerfile
    ports:
      - "9099:8080"
    depends_on:
      - measurement-service
    networks:
      - extranet
      - intranet
  measurement-service:
    image: measurement-service
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports:
      - "9091:80"
    depends_on:
      - measurement-db
    networks:
      - extranet
      - intranet
  patient-service:
    image: patient-service
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - patient-db
      - measurement-service
    networks:
      - extranet
      - intranet
  measurement-db:
    image: mongo:latest
    container_name: measurement-db
    ports:
      - "27016:27017"
    volumes:
      - measurement_data:/data/db
    networks:
      - intranet
  patient-db:
    image: mongo:latest
    container_name: patient-db
    ports:
      - "27017:27017"
    volumes:
      - patient_data:/data/db
    networks:
      - intranet

volumes:
  measurement_data:
  patient_data:
    
networks:
  intranet:
    external: false
  extranet:
    external: true

    