name: Build + push to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker images
      run: docker-compose build

    # Optionally, run some tests here if you have them

    - name: Push the Docker images
      run: |
        docker-compose push doctor-ui
        docker-compose push patient-ui
        docker-compose push measurement-service
        docker-compose push patient-service

    # Optional step to logout from Docker Hub
    - name: Logout of Docker Hub
      run: docker logout

