name: Build + push to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: minsygehus_prod

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Setup Python (to run the version script)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Fetch the latest tag
      id: get-latest-tag
      run: |
        TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/tags \
          -H "Authorization: token ${{ secrets.GH_PAT }}" | jq -r '.[0].name' | head -n 1)
        if [[ "$TAG" == "null" ]]; then
          echo "::set-output name=tag::1.0.0" # default to 1.0.0 if no tags found
        else
          echo "::set-output name=tag::$TAG"
        fi

    - name: Increment version
      id: increment-version
      run: |
        CURRENT_VERSION=${{ steps.get-latest-tag.outputs.tag }}
        IFS='.' read -ra ADDR <<< "$CURRENT_VERSION"
        PATCH=${ADDR[2]}
        NEW_PATCH=$(($PATCH + 1))
        NEW_VERSION="${ADDR[0]}.${ADDR[1]}.$NEW_PATCH"
        echo "::set-output name=new-version::$NEW_VERSION"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker images
      run: docker-compose build

    - name: Tag and push Docker images
      run: |
        docker tag doctor-ui:latest sergiomm000/minsygehus:doctor-ui-${{ steps.increment-version.outputs.new-version }}
        docker tag patient-ui:latest sergiomm000/minsygehus:patient-ui-${{ steps.increment-version.outputs.new-version }}
        docker tag measurement-service:latest sergiomm000/minsygehus:measurement-service-${{ steps.increment-version.outputs.new-version }}
        docker tag patient-service:latest sergiomm000/minsygehus:patient-service-${{ steps.increment-version.outputs.new-version }}
        docker push sergiomm000/minsygehus:doctor-ui-${{ steps.increment-version.outputs.new-version }}
        docker push sergiomm000/minsygehus:patient-ui-${{ steps.increment-version.outputs.new-version }}
        docker push sergiomm000/minsygehus:measurement-service-${{ steps.increment-version.outputs.new-version }}
        docker push sergiomm000/minsygehus:patient-service-${{ steps.increment-version.outputs.new-version }}

    - name: Configure git with GH_PAT
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

    - name: Create new tag and push
      run: |
        git tag ${{ steps.increment-version.outputs.new-version }}
        git push origin ${{ steps.increment-version.outputs.new-version }}

    - name: Logout of Docker Hub
      run: docker logout
